[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
dark_sol = "CF1x7n8CDcjwJcRfPwDCecqqR2PNAmV7f79zPPU9rPip"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ZATAARA/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
